name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Compile tests
        run: yarn test-compile

      - name: Package extension
        run: npx @vscode/vsce package --allow-star-activation -o svn-scm.vsix

      - name: Upload VSIX
        uses: actions/upload-artifact@v6
        with:
          name: svn-scm-${{ github.sha }}
          path: svn-scm.vsix

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn

      - name: Install Subversion
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Install Subversion
        if: runner.os == 'Windows'
        run: choco install svn --no-progress --yes

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Compile tests
        run: yarn test-compile

      - name: Run integration tests
        if: runner.os == 'Linux'
        run: xvfb-run -a yarn test
        env:
          CODE_VERSION: 1.109.2

      - name: Run integration tests
        if: runner.os == 'Windows'
        run: yarn test
        env:
          CODE_VERSION: 1.109.2
