name: Temporary external info optimization

on:
  push:
    branches:
      - "perf/skip-unused-external-info"
    paths:
      - ".github/workflows/temp-external-info-perf.yml"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo ready
